### ISSUE TITLE
Не создаются задачи

### ISSUE THREAD

**Issue by kirush0280** [xor2016/majordomo-todoer#3]
Нажимаю "Добавить задачу"
Задача: test
категория: Обслуживание
Сроки для задачи: "Весь день"
Начало/Конец: ставлю следующий день
Нажимаю "Сохранить"
и ничего не происходит, как будто задача не сохраняется.
![2022-04-26_07-34-10](https://user-images.githubusercontent.com/13412942/165221865-f8bde1a3-932e-4a13-bc5b-94a7446532dd.png)
Majordomo Альфа последняя
"

**Comment by xor2016** [comment]
попробуйте последний фикс, вроде, поправилось. в админке не создавалось, да. а я преимущественно в обычном режиме работаю и просмотрел(

**Comment by kirush0280** [comment]
Решено. Спасибо огромное.
